language: python
python:
- 3.7

before_install:
 - pip install coverage
 - pip install --upgrade 'importlib-metadata > 4'
install:
 - pip install ".[test]" .
script:
 - coverage run -m unittest discover
after_success:
 - bash <(curl -s https://codecov.io/bash)
